import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";
import Nav from "../../components/Home/Navbar/Nav";
import Hero from "../../components/Home/Hero/Hero"
import Destination from "../../components/Home/Destination/Destination";

const font = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Travel Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <Nav />
        <Hero />
        <Destination />
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
