import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";
import Nav from "../../components/Home/Navbar/Nav";
import Hero from "../../components/Home/Hero/Hero"
import Destination from "../../components/Home/Destination/Destination";
import Hotel from "../../components/Home/Hotel/Hotel";
import WhyChooseUs from "../../components/Home/WhyChooseUs/WhyChooseUs";
import Review from "../../components/Home/Reviews/Review";
import Newsletter from "../../components/Home/NewsLetter/Newsletter";
import Footer from "../../components/Home/Footer/Footer";
import TopDestinations from "../../components/Home/TopDestinations/TopDestinations";

const font = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Travel Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <Nav />
        <Hero />
        <Destination />
        <Hotel />
        <WhyChooseUs />
        <TopDestinations />
        <Review />
        <Newsletter />
        <Footer />
        {children}
      </body>
    </html>
  );
}
